--- # network build playbook

- name: "PLAY 1: Configure All LAN Switches"
  hosts: lan
  tags: lan
  gather_facts: false
  
  tasks:
    - name: "Configure Hostname and Domain Name"
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"
        lookup_enabled: no
        name_servers: "{{ name_servers }}"
    - name: "Configure NTP"
      ios_ntp:
        server: "{{ ntp_servers }}"
        logging: true
        state: present
    - name: "P1T3: Configure Interfaces"
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ item.name  }}"
          description: "{{ item.description }}"
          duplex: "{{ intf_duplex }}"
          mtu: "{{ intf_mtu }}"
          enabled: true
      with_items: "{{ interfaces[inventory_hostname] }}"
      register: ios_intf
# this is here to debug the variable the previous play was set to
    - name: debug the iso_intf
      ansible.builtin.debug:
        var: ios_intf