--- # network build playbook

- name: "PLAY 1: Configure All LAN Switches"
  hosts: lan
  tags: lan
  gather_facts: false
  
  tasks:
    - name: "Configure Hostname and Domain Name"
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"
        lookup_enabled: no
        name_servers: "{{ name_servers }}"
    - name: "Configure NTP"
      ios_ntp:
        server: "{{ ntp_servers }}"
        logging: true
        state: present
    - name: "P1T3: Configure Interfaces"
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ item.name  }}"
          description: "{{ item.description }}"
          duplex: "{{ intf_duplex }}"
          mtu: "{{ intf_mtu }}"
          enabled: true
      with_items: "{{ interfaces[inventory_hostname] }}"
      register: ios_intf
# this is here to debug the variable the previous play was set to
    - name: debug the iso_intf
      ansible.builtin.debug:
        var: ios_intf

    - name: "P1T4: Create L2 VLAN"
      cisco.ios.ios_config:
        lines:
          - switchport trunk encapsulation dot1q
        parents: interface {{item.name}}
      with_items: "{{ interfaces[inventory_hostname] | selectattr('mode','equalto','trunk') | list }}"

    - name: "Configure L2 Trunks"
      cisco.ios.ios_l2_interfaces:
        config:
        - name: "{{item.name}}"
          mode: "{{item.mode}}"
          trunk:
            allowed_vlans: 10,20,100
      with_items: "{{ interfaces[inventory_hostname] | selectattr('mode','equalto','trunk') | list }}"

    - name: "P1T4: Create L2 VLANs"
      cisco.ios.ios_vlans:
        config:
        - name: "{{item.name}}"
          vlan_id: "{{item.vlan_id}}"
          state: active
      with_items: "{{vlans}}"
      tags: vlans

    - name: "Configure Access Ports"
      cisco.ios.ios_l2_interfaces:
        config:
        - name: "{{item.name}}"
          mode: "{{item.mode}}"
          access:
            vlan: "{{item.vlan}}"
      with_items: "{{ interfaces[inventory_hostname] | selectattr('mode','equalto','access') | list }}"

        
       
        
