--- # network build playbook

- name: "PLAY 1: Configure All LAN Switches"
  hosts: lan
  tags: lan
  gather_facts: false
  
  tasks:
    - name: "Configure Hostname and Domain Name"
      ios_system:
        hostname: "{{ inventory_hostname }}"
        #domain_name: "{{ domain_name }}"
        lookup_enabled: no
        name_servers: "{{ name_servers }}"
    - name: "Configure NTP"
      ios_ntp:
        server: "{{ ntp_servers }}"
        logging: true
        state: present