vlans:
  - name: Data
    vlan_id: 10
  - name: Voice
    vlan_id: 20
  - name: Web
    vlan_id: 100

interfaces:
  core01:
    - name: GigabitEthernet0/2
      description: To access01
      mode: trunk     
    - name: GigabitEthernet0/3
      description: to access02
      mode: trunk
    - name: GigabitEthernet0/1
      description: to core02
      mode:
    - name: GigabitEthernet1/0
      description: Management
      mode:
    - name: GigabitEthernet0/0
      description: to wan01
      mode:
  core02:
    - name: GigabitEthernet0/1
      description: to core01
      mode:
    - name: GigabitEthernet0/2
      description: to access01
      mode:
    - name: GigabitEthernet0/3
      description: to access02
      mode:
    - name: GigabitEthernet1/0
      description: Management
      mode:

  access01:
    - name: GigabitEthernet0/0
      description: vlan 10
      mode: access
      vlan: 10
    - name: GigabitEthernet0/2
      description: Management
      mode:
    - name: GigabitEthernet0/1
      description: to core01
      mode: trunk
    - name: GigabitEthernet0/3
      description: to core02
      mode: trunk
  access02:
    - name: GigabitEthernet0/0
      description: vlan 20
      mode: access
      vlan: 20
    - name: GigabitEthernet0/1
      description: vlan 100
      mode: access
      vlan: 100
    - name: GigabitEthernet0/2
      description: Management
      mode:
    - name: GigabitEthernet0/3
      description: to core02
      mode: trunk
    - name: GigabitEthernet1/0
      description: to core01
      mode: turnk